package biodanza.vista;

import java.util.LinkedList;
import java.util.Set;

import javax.swing.AbstractListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

import biodanza.modelo.Biodanza;
import biodanza.modelo.Cancion;
import biodanza.modelo.CancionReal;
import biodanza.modelo.MusicPlayer;
import biodanza.modelo.Similitud;

public class AgregarEtiquetasG extends javax.swing.JDialog
{
    private static final long serialVersionUID = 6803338778597201581L;

    Object[] carr;
    LinkedList<Cancion> aEtiquetar;
    Cancion actual;
    String nombreColeccion;

    /** Creates new form BuscarCancion */
    public AgregarEtiquetasG(java.awt.Frame parent, boolean modal, LinkedList<Cancion> aE)
    {
        super(parent, modal);
        aEtiquetar = aE;
        actual = aEtiquetar.poll();
        nombreColeccion = "";
        for(char c : actual.getAlbum().padre.nombre.toCharArray())
            if(c >= 'A' && c <= 'Z')
                nombreColeccion += c;
        initComponents();
        actualizarCancion();
        ultimaEtiqueta.setText("");
        ultimaEtiqueta.updateUI();
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e)
            {
                MusicPlayer.stopPlayer();
            }
        });
    }

    private void actualizarCancion()
    {
        coleccion.setText(actual.getAlbum().padre.nombre);
        album.setText(actual.getAlbum().nombre);
        cancion.setText(actual.getNombre());
        coleccion.updateUI();
        album.updateUI();
        cancion.updateUI();
        String[] etiquetas = actual.getEtiquetas();
        carr = new Object[etiquetas.length];
        for(int i = 0; i < etiquetas.length; i++)
            carr[i] = etiquetas[i];
        actualizarLm();
    }

    private void actualizarLm()
    {
        ListModel lm = new AbstractListModel()
        {
            private static final long serialVersionUID = 3265324191683068280L;

            public int getSize()
            {
                return carr.length;
            }

            public Object getElementAt(int index)
            {
                return carr[index];
            }
        };
        encontrados.setModel(lm);
        encontrados.updateUI();
    }

    /**
     * Busca las palabras dadas en la cadena searchText y retorna un conjunto
     * con los resultados.
     * 
     * @param searchText
     *            Palabras a buscar
     * @param nresults
     *            Máximo número de resultados a retornar
     * @return
     */
    Set<Object> buscar(String searchText, int nresults)
    {
        Similitud s = new Similitud(new CancionReal(searchText, "", null));
        int nwords = s.palabras.size();
        int count = 0;
        for(String c : Biodanza.darEtiquetas())
        {
            if(!c.startsWith(nombreColeccion))
                continue;
            if(s.adicionar(c, nwords))
                if(++count >= nresults)
                    break;
        }
        return s.similares.keySet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        txtSearchText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        encontrados = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cancion = new javax.swing.JLabel();
        album = new javax.swing.JLabel();
        coleccion = new javax.swing.JLabel();
        ultimaEtiqueta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Etiqueta");

        txtSearchText.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtSearchTextActionPerformed(evt);
            }
        });

        encontrados.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

            public int getSize()
            {
                return strings.length;
            }

            public Object getElementAt(int i)
            {
                return strings[i];
            }
        });
        jScrollPane1.setViewportView(encontrados);

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelActionPerformed(evt);
            }
        });

        cancion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        cancion.setText("Nombre cancion");

        album.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        album.setText("Nombre album");

        coleccion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        coleccion.setText("Nombre coleccion");

        ultimaEtiqueta.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        ultimaEtiqueta.setText("Ultima etiqueta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            layout
                .createSequentialGroup()
                .addGroup(
                    layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                            layout
                                .createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(
                                    layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(coleccion)
                                        .addComponent(album)
                                        .addComponent(cancion)
                                        .addComponent(jLabel1)
                                        .addComponent(txtSearchText)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING,
                                            javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                        .addComponent(ultimaEtiqueta, javax.swing.GroupLayout.Alignment.TRAILING,
                                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE)))
                        .addGroup(
                            layout
                                .createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 131,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            layout
                .createSequentialGroup()
                .addContainerGap()
                .addComponent(coleccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(album)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ultimaEtiqueta)
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchText, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchTextActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_txtSearchTextActionPerformed
        String searchText = txtSearchText.getText();
        Set<Object> s = buscar(searchText, 30);
        carr = s.toArray();
        actualizarLm();
    }// GEN-LAST:event_txtSearchTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_jButton1ActionPerformed
        String s = (String) encontrados.getSelectedValue();
        if(s == null)
            if(!txtSearchText.getText().trim().isEmpty())
                s = nombreColeccion + " - " + txtSearchText.getText();
            else
                s = "";
        s = s.toUpperCase();
        if(!s.trim().isEmpty())
        {
            actual.agregarEtiqueta(s);
            Biodanza.agregarEtiqueta(s);
            ultimaEtiqueta.setText(s);
            ultimaEtiqueta.updateUI();
        }
        else
        {
            ultimaEtiqueta.setText("");
            ultimaEtiqueta.updateUI();
        }
        actual = aEtiquetar.poll();
        if(actual == null)
        {
            JOptionPane.showMessageDialog(this, "Termino de etiquetar");
            setVisible(false);
            return;
        }
        actualizarCancion();
    }// GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_btnCancelActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Desea dejar de etiquetar esta cancion?", "Etiquetar cancion",
            JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION)
            return;
        actual = aEtiquetar.poll();
        if(actual == null)
        {
            JOptionPane.showMessageDialog(this, "Termino de etiquetar");
            setVisible(false);
            return;
        }
        actualizarCancion();
        ultimaEtiqueta.setText("");
        ultimaEtiqueta.updateUI();
    }// GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel album;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel cancion;
    private javax.swing.JLabel coleccion;
    private javax.swing.JList encontrados;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtSearchText;
    private javax.swing.JLabel ultimaEtiqueta;
    // End of variables declaration//GEN-END:variables
}
