package biodanza.vista;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Set;

import javax.swing.AbstractListModel;
import javax.swing.ListModel;

import biodanza.modelo.Biodanza;
import biodanza.modelo.Cancion;
import biodanza.modelo.CancionReal;
import biodanza.modelo.MusicPlayer;
import biodanza.modelo.Similitud;

public class BuscarCancionG extends javax.swing.JDialog
{
    private static final long serialVersionUID = 6803338778597201581L;

    Object[] carr;
    DialogCaller dc = null;
    private volatile MusicPlayer playing = null;

    /** Creates new form BuscarCancion */
    public BuscarCancionG(java.awt.Frame parent, boolean modal, DialogCaller d)
    {
        super(parent, modal);
        dc = d;
        initComponents();
        carr = new Object[0];
        ListModel lm = new AbstractListModel()
        {
            private static final long serialVersionUID = -817259084873187257L;

            public int getSize()
            {
                return carr.length;
            }

            public Object getElementAt(int index)
            {
                return carr[index];
            }
        };
        encontrados.setModel(lm);
        encontrados.updateUI();
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e)
            {
                MusicPlayer.stopPlayer();
            }
        });
    }

    void setCaller(DialogCaller a)
    {
        this.dc = a;
    }

    /**
     * Busca las palabras dadas en la cadena searchText y retorna un conjunto
     * con los resultados.
     * 
     * @param searchText
     *            Palabras a buscar
     * @param nresults
     *            Máximo número de resultados a retornar
     * @return
     */
    Set<Object> buscar(String searchText, int nresults)
    {
        // Assume that searchText is the name of a song
        Similitud s = new Similitud(new CancionReal(searchText, "", null));
        int nwords = s.palabras.size();
        int count = 0;
        for(String e : Biodanza.darEtiquetas())
        {
            if(s.adicionar(e, nwords))
                if(++count >= nresults)
                    break;
        }
        if(count <= nresults)
        {
            for(Cancion c : Biodanza.todasCanciones)
            {
                if(s.adicionar(c, nwords))
                    if(++count >= nresults)
                        break;
            }
        }
        s.exacto = false;
        if(count <= nresults)
        {
            for(String e : Biodanza.darEtiquetas())
            {
                if(s.adicionar(e, nwords))
                    if(++count >= nresults)
                        break;
            }
        }
        if(count <= nresults)
        {
            for(Cancion c : Biodanza.todasCanciones)
            {
                if(s.adicionar(c, nwords))
                    if(++count >= nresults)
                        break;
            }
        }
        return s.similares.keySet();
    }

    private static class CancionWrap
    {
        Cancion original;
        String nombre;

        CancionWrap(Cancion o, String n)
        {
            original = o;
            nombre = n;
        }

        @Override
        public String toString()
        {
            return nombre;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        txtSearchText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        encontrados = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Palabras");

        txtSearchText.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtSearchTextActionPerformed(evt);
            }
        });

        encontrados.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

            public int getSize()
            {
                return strings.length;
            }

            public Object getElementAt(int i)
            {
                return strings[i];
            }
        });
        encontrados.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                encontradosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(encontrados);

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelActionPerformed(evt);
            }
        });

        btnPlay.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPlayActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            layout
                .createSequentialGroup()
                .addGroup(
                    layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                            layout
                                .createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(
                                    layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(
                                            layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(
                                                    layout
                                                        .createSequentialGroup()
                                                        .addComponent(txtSearchText)
                                                        .addPreferredGap(
                                                            javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton2))
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    536, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(
                            layout
                                .createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 131,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 131,
                                    javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap(26, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            layout
                .createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(
                    layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearchText, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchTextActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_txtSearchTextActionPerformed
        String searchText = txtSearchText.getText();
        Set<Object> s = buscar(searchText, 30);
        carr = s.toArray();
        for(int i = 0; i < carr.length; i++)
            if(carr[i] instanceof String)
                carr[i] = "+ " + (String) carr[i];
        ListModel lm = new AbstractListModel()
        {
            private static final long serialVersionUID = 3265324191683068280L;

            public int getSize()
            {
                return carr.length;
            }

            public Object getElementAt(int index)
            {
                return carr[index];
            }
        };
        encontrados.setModel(lm);
    }// GEN-LAST:event_txtSearchTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_jButton1ActionPerformed
        MusicPlayer.stopPlayer();
        Object c = encontrados.getSelectedIndex() == -1 ? null : carr[encontrados.getSelectedIndex()];
        if(c != null && c instanceof CancionWrap)
        {
            CancionWrap cW = (CancionWrap) c;
            c = cW.original;
        }
        if(c != null && c instanceof String)
        {
            String s = (String) c;
            c = s.substring(2);
        }
        if(dc != null)
            if(c != null)
                dc.setAnswer(DialogCaller.OK, c);
            else
                dc.setAnswer(DialogCaller.CANCEL, null);
        setVisible(false);
    }// GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_btnCancelActionPerformed
        MusicPlayer.stopPlayer();
        if(dc != null)
            dc.setAnswer(DialogCaller.CANCEL, null);
        setVisible(false);
    }// GEN-LAST:event_btnCancelActionPerformed

    private void encontradosMouseClicked(java.awt.event.MouseEvent evt)
    {// GEN-FIRST:event_encontradosMouseClicked
        if(evt.getClickCount() == 2)
        {
            int indice = encontrados.getSelectedIndex();
            Object c = indice == -1 ? null : carr[indice];
            if(c == null || !(c instanceof String))
            {
                if(c != null)
                {
                    synchronized(this)
                    {
                        if(playing != null)
                            btnPlayActionPerformed(null);
                        btnPlayActionPerformed(null);
                    }
                }
                return;
            }
            String etiqueta = (String) c;
            ArrayList<Object> todos = new ArrayList<Object>();
            for(int i = 0; i < indice; i++)
                todos.add(carr[i]);
            if(etiqueta.charAt(0) == '+')
            {
                todos.add("- " + etiqueta.substring(2));
                indice++;
                Cancion[] canciones = Biodanza.darCancionesEtiqueta(etiqueta.substring(2).trim()).clone();
                Arrays.sort(canciones);
                for(Cancion cancion : canciones)
                    todos.add(new CancionWrap(cancion, "    " + cancion.getNombre()));
            }
            else
            {
                todos.add("+ " + etiqueta.substring(2));
                indice++;
                while(indice < carr.length && (carr[indice] instanceof CancionWrap))
                    indice++;
            }
            for(int i = indice; i < carr.length; i++)
                todos.add(carr[i]);
            carr = todos.toArray();
            ListModel lm = new AbstractListModel()
            {
                private static final long serialVersionUID = -817259084873187257L;

                public int getSize()
                {
                    return carr.length;
                }

                public Object getElementAt(int index)
                {
                    return carr[index];
                }
            };
            encontrados.setModel(lm);
            encontrados.updateUI();
        }
    }// GEN-LAST:event_encontradosMouseClicked

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_btnPlayActionPerformed
        synchronized(this)
        {
            Object c = encontrados.getSelectedIndex() == -1 ? null : carr[encontrados.getSelectedIndex()];
            if(playing == null)
            {
                if(!(c instanceof CancionWrap) && !(c instanceof Cancion))
                    return;
                if(c instanceof CancionWrap)
                {
                    CancionWrap cW = (CancionWrap) c;
                    c = cW.original;
                }
                playing = MusicPlayer.playSong((Cancion) c, new Runnable()
                {
                    public void run()
                    {
                        if(playing != null && playing.termino)
                            btnPlayActionPerformed(null);
                    }
                });
                if(playing != null)
                {
                    playing.play();
                    btnPlay.setText("Stop");
                }
            }
            else
            {
                playing.stop();
                playing = null;
                btnPlay.setText("Play");
            }
        }
    }// GEN-LAST:event_btnPlayActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_jButton2ActionPerformed
        txtSearchTextActionPerformed(evt);
    }// GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPlay;
    private javax.swing.JList encontrados;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtSearchText;
    // End of variables declaration//GEN-END:variables
}
