package biodanza.vista;

import java.awt.KeyEventPostProcessor;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import biodanza.modelo.Cancion;
import biodanza.modelo.ClaseBiodanza;
import biodanza.modelo.MusicPlayer;

public class ClaseEnProgresoG extends javax.swing.JDialog implements KeyListener
{

    private static final long serialVersionUID = -2406387885950943432L;

    private ClaseBiodanza clase;
    private int actual = 0;
    private static volatile ClaseEnProgresoG claseActual;

    /** Creates new form NewJDialog1 */
    public ClaseEnProgresoG(java.awt.Frame parent, boolean modal, ClaseBiodanza c)
    {
        super(parent, modal);
        clase = c;
        initComponents();
        setFocusable(true);
        setFocusableWindowState(true);
        final KeyEventPostProcessor despachador = new KeyEventPostProcessor()
        {
            @Override
            public boolean postProcessKeyEvent(KeyEvent e)
            {
                if(e.getID() == KeyEvent.KEY_PRESSED)
                    claseActual.keyPressed(e);
                return true;
            }
        };
        KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventPostProcessor(despachador);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e)
            {
                KeyboardFocusManager.getCurrentKeyboardFocusManager().removeKeyEventPostProcessor(despachador);
                MusicPlayer.stopPlayer();
            }
        });
        ClaseEnProgresoG claseE = this;
        claseActual = claseE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        ejercicioV1 = new biodanza.vista.EjercicioV(clase.darEjercicio(actual), true);
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        ejercicioV2 = new biodanza.vista.EjercicioV(actual == clase.darTamano() - 1 ? null
            : clase.darEjercicio(actual + 1), false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1440, 850));

        jButton2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton2.setText("Anterior");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Andale Mono", 0, 15)); // NOI18N
        jLabel1.setText("Siguiente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout
            .setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                    layout
                        .createSequentialGroup()
                        .addGroup(
                            layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(
                                    layout
                                        .createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(
                                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSeparator1).addComponent(jSeparator2)))
                                .addComponent(ejercicioV1, javax.swing.GroupLayout.DEFAULT_SIZE, 1555, Short.MAX_VALUE)
                                .addGroup(
                                    layout
                                        .createSequentialGroup()
                                        .addGroup(
                                            layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(
                                                    layout
                                                        .createSequentialGroup()
                                                        .addGap(20, 20, 20)
                                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                            javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(
                                                    layout.createSequentialGroup().addGap(10, 10, 10)
                                                        .addComponent(jLabel1))).addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(ejercicioV2, javax.swing.GroupLayout.Alignment.TRAILING,
                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE)).addGap(0, 0, 0)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            layout
                .createSequentialGroup()
                .addGap(10, 12, 12)
                .addGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton2)
                        .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ejercicioV1, javax.swing.GroupLayout.PREFERRED_SIZE, 375,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ejercicioV2, javax.swing.GroupLayout.PREFERRED_SIZE, 257,
                    javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0, 0, 0)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_jButton2ActionPerformed
        if(ejercicioV1 != null && ejercicioV1.isPlaying())
            ejercicioV1.stop();
        if(ejercicioV2 != null && ejercicioV2.isPlaying())
            ejercicioV2.stop();
        actual--;
        if(actual == -1)
            actual++;
        recargarEjercicios();
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_jButton1ActionPerformed
        if(ejercicioV1 != null && ejercicioV1.isPlaying())
            ejercicioV1.stop();
        if(ejercicioV2 != null && ejercicioV2.isPlaying())
            ejercicioV2.stop();
        actual++;
        if(actual == clase.darTamano())
            actual--;
        recargarEjercicios();
    }// GEN-LAST:event_jButton1ActionPerformed

    private void recargarEjercicios()
    {
        ejercicioV1.cambiarEjercicio(clase.darEjercicio(actual));
        ejercicioV2.cambiarEjercicio(actual == clase.darTamano() - 1 ? null : clase.darEjercicio(actual + 1));
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private biodanza.vista.EjercicioV ejercicioV1;
    private biodanza.vista.EjercicioV ejercicioV2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;

    // End of variables declaration//GEN-END:variables

    public void keyTyped(KeyEvent e)
    {
    }

    public void keyPressed(KeyEvent e)
    {
        Cancion cActual = ejercicioV1.ejercicio == null ? null : ejercicioV1.ejercicio.getCancion();
        if(e.getKeyCode() == KeyEvent.VK_UP)
        {
            ejercicioV1.play();
        }
        else if(e.getKeyCode() == KeyEvent.VK_DOWN)
        {
            if(cActual == null)
                return;
            if(ejercicioV1.isPlaying() && !ejercicioV1.isPaused())
                ejercicioV1.pause();
            else if(ejercicioV1.isPlaying() && ejercicioV1.isPaused())
                ejercicioV1.stop();
        }
        else if(e.getKeyCode() == KeyEvent.VK_LEFT)
            jButton2ActionPerformed(null);
        else if(e.getKeyCode() == KeyEvent.VK_RIGHT)
            jButton1ActionPerformed(null);

    }

    public void keyReleased(KeyEvent e)
    {
    }
}
