package biodanza.vista;

import biodanza.modelo.Ejercicio;
import biodanza.modelo.MusicPlayer;

public class EjercicioV extends javax.swing.JPanel
{

    private static final long serialVersionUID = 4887384116504762074L;

    volatile Ejercicio ejercicio;
    volatile MusicPlayer player;
    boolean botones;

    /** Creates new form IPrincipal */
    public EjercicioV(Ejercicio e, boolean b)
    {
        ejercicio = e;
        botones = b;
        initComponents();
        bind();
    }

    public EjercicioV()
    {
        initComponents();
    }

    public void cambiarEjercicio(Ejercicio e)
    {
        ejercicio = e;
        bind();
    }

    final void bind()
    {
        if(ejercicio != null)
        {
            lblTitle.setText(ejercicio.getNombre());
            lblObj.setText(ejercicio.getObjetivo());
            if(ejercicio.getCancion() != null)
            {
                cmdStop.setVisible(false);
                cmdPause.setVisible(false);
                cmdPlay.setVisible(true);
                lblSong.setText(ejercicio.getCancion().toString());
            }
            else
            {
                cmdStop.setVisible(false);
                cmdPause.setVisible(false);
                cmdPlay.setVisible(false);
                lblSong.setText("Sin cancion");
            }
        }
        else
        {
            lblTitle.setText("");
            lblObj.setText("");
            cmdStop.setVisible(false);
            cmdPause.setVisible(false);
            cmdPlay.setVisible(false);
            lblSong.setText("Sin cancion");
        }
        if(!botones)
        {
            cmdStop.setVisible(false);
            cmdPause.setVisible(false);
            cmdPlay.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblObj = new javax.swing.JTextArea();
        lblSong = new javax.swing.JLabel();
        cmdPlay = new javax.swing.JButton();
        cmdPause = new javax.swing.JButton();
        cmdStop = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTitle.setText("Caminar alegre");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        lblObj.setEditable(false);
        lblObj.setColumns(15);
        lblObj.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblObj.setLineWrap(true);
        lblObj.setRows(5);
        lblObj
            .setText("Tomados de las manos sintiendo la presencia de nuestros compañeros \ncerramos\nlos ojos.\n Y nos movemos suavemente al ritmo de la música. \n\n\n\nSintiendo la música vamos construyendo vínculos  nutriéndonos desde el dialogo de \nnuestros gestos el dialogo de la mirada  de la sonrisa.\ncddfs\ndsf\n\ndsf\nsfd\nsdf\n");
        lblObj.setWrapStyleWord(true);
        jScrollPane1.setViewportView(lblObj);

        lblSong.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblSong.setText("nombre cancion");

        cmdPlay.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        cmdPlay.setText("Play");
        cmdPlay.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmdPlayActionPerformed(evt);
            }
        });

        cmdPause.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        cmdPause.setText("Pause");
        cmdPause.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmdPauseActionPerformed(evt);
            }
        });

        cmdStop.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        cmdStop.setText("Stop");
        cmdStop.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmdStopActionPerformed(evt);
            }
        });

        lblTitle1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTitle1.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            layout
                .createSequentialGroup()
                .addContainerGap()
                .addGroup(
                    layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addComponent(jScrollPane1).addContainerGap())
                        .addGroup(
                            layout
                                .createSequentialGroup()
                                .addGroup(
                                    layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(
                                            layout
                                                .createSequentialGroup()
                                                .addComponent(lblSong)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 855,
                                            Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 181,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(
                                    layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmdPause, javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmdPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 102,
                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmdStop, javax.swing.GroupLayout.PREFERRED_SIZE, 98,
                                    javax.swing.GroupLayout.PREFERRED_SIZE).addGap(122, 122, 122)))));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            layout
                .createSequentialGroup()
                .addContainerGap()
                .addGroup(
                    layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                            layout
                                .createSequentialGroup()
                                .addGroup(
                                    layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                            javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(lblTitle1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSong))
                        .addGroup(
                            layout.createSequentialGroup().addComponent(cmdPlay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdPause)).addComponent(cmdStop)).addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    public void play()
    {
        cmdPlayActionPerformed(null);
    }

    public void pause()
    {
        cmdPauseActionPerformed(null);
    }

    public void stop()
    {
        cmdStopActionPerformed(null);
    }

    public boolean isPlaying()
    {
        synchronized(this)
        {
            return player != null && player.isPlaying();
        }
    }

    public boolean isPaused()
    {
        synchronized(this)
        {
            return player != null && player.isPaused();
        }
    }

    private static String darMinutosSegundos(long valor)
    {
        valor /= 1000000;
        int minutos = (int) (valor / 60);
        int segundos = (int) (valor % 60);
        return minutos + ":" + (segundos < 10 ? "0" + segundos : segundos);
    }

    private void cmdPlayActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_cmdPlayActionPerformed
        synchronized(this)
        {
            if(player == null)
                player = MusicPlayer.playSong(ejercicio.getCancion(), new Runnable()
                {
                    public void run()
                    {
                        if(player != null && !player.termino)
                        {
                            if(player.frames != 0)
                                lblTitle1
                                    .setText(darMinutosSegundos((long) (player.duration * (player.currentFrame / (double) (player.frames))))
                                        + " / " + darMinutosSegundos(player.duration));
                        }
                        else
                            cmdStopActionPerformed(null);
                    }
                });
            else if(player.isPlaying() && !player.isPaused())
                return;
            player.play();
        }
        cmdStop.setVisible(true);
        cmdPause.setVisible(true);
        cmdPlay.setVisible(false);
    }// GEN-LAST:event_cmdPlayActionPerformed

    private void cmdPauseActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_cmdPauseActionPerformed
        synchronized(this)
        {
            if(player != null)
                player.pause();
        }
        cmdStop.setVisible(true);
        cmdPause.setVisible(false);
        cmdPlay.setVisible(true);
    }// GEN-LAST:event_cmdPauseActionPerformed

    private void cmdStopActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_cmdStopActionPerformed
        synchronized(this)
        {
            if(player != null)
            {
                player.stop();
                player = null;
            }
        }
        lblTitle1.setText(" ");
        cmdStop.setVisible(false);
        cmdPause.setVisible(false);
        cmdPlay.setVisible(true);
    }// GEN-LAST:event_cmdStopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdPause;
    private javax.swing.JButton cmdPlay;
    private javax.swing.JButton cmdStop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lblObj;
    private javax.swing.JLabel lblSong;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    // End of variables declaration//GEN-END:variables
}
