package biodanza.vista;

import java.io.File;

import javax.swing.AbstractListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

import biodanza.modelo.Cancion;
import biodanza.modelo.MusicPlayer;
import biodanza.modelo.Similitud;

public class RepetidosG extends javax.swing.JPanel
{

    private static final long serialVersionUID = 132461013174204615L;

    Similitud s;
    private volatile MusicPlayer playing = null;

    /** Creates new form Repetidos */
    public RepetidosG(Similitud s)
    {
        initComponents();
        cmdStop.setVisible(false);
        this.s = s;
        s.similares.put(s.ppal, s.ppal.toString().length());
        dataBind();
    }

    final void dataBind()
    {
        lblCancion.setText(s.ppal.toString());
        ListModel lm = new AbstractListModel()
        {

            private static final long serialVersionUID = -3212615299011139249L;

            public int getSize()
            {
                return s.similares.size();
            }

            public Object getElementAt(int index)
            {
                Object array[] = s.similares.keySet().toArray();
                return array[index];
            }
        };
        listRepetidas.setModel(lm);
    }

    public static void main(String[] args)
    {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        popLista = new javax.swing.JPopupMenu();
        mnuDeleteSong = new javax.swing.JMenuItem();
        mnuListenSong = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        lblCancion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmdStop = new javax.swing.JButton();
        listRepetidas = new javax.swing.JList();

        mnuDeleteSong.setText("Eliminar canción");
        mnuDeleteSong.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuDeleteSongActionPerformed(evt);
            }
        });
        popLista.add(mnuDeleteSong);
        mnuDeleteSong.getAccessibleContext().setAccessibleName("Eliminar");

        mnuListenSong.setText("Escuchar canción");
        mnuListenSong.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuListenSongActionPerformed(evt);
            }
        });
        popLista.add(mnuListenSong);

        jLabel1.setText("Canción:");

        lblCancion.setText("Nombre de la canción");

        jLabel3.setText("Posibles repetidas:");

        cmdStop.setText("Stop");
        cmdStop.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmdStopActionPerformed(evt);
            }
        });

        listRepetidas.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

            public int getSize()
            {
                return strings.length;
            }

            public Object getElementAt(int i)
            {
                return strings[i];
            }
        });
        listRepetidas.setToolTipText("Selecciona las canciones y has click en ellas con el botón derecho del mouse");
        listRepetidas.setAutoscrolls(false);
        listRepetidas.setComponentPopupMenu(popLista);
        listRepetidas.setDropMode(javax.swing.DropMode.ON);
        listRepetidas.setSelectedIndex(0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.LEADING,
                                layout
                                    .createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblCancion, javax.swing.GroupLayout.DEFAULT_SIZE, 314,
                                        Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING).addComponent(cmdStop))
                    .addContainerGap())
            .addGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                    layout
                        .createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(listRepetidas, javax.swing.GroupLayout.PREFERRED_SIZE, 384,
                            javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0, 13, Short.MAX_VALUE))));
        layout.setVerticalGroup(layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
                            .addComponent(lblCancion))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                    .addComponent(cmdStop, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                    layout
                        .createSequentialGroup()
                        .addGap(0, 53, Short.MAX_VALUE)
                        .addComponent(listRepetidas, javax.swing.GroupLayout.PREFERRED_SIZE, 211,
                            javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0, 54, Short.MAX_VALUE))));
    }// </editor-fold>//GEN-END:initComponents

    private void mnuDeleteSongActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_mnuDeleteSongActionPerformed
        Cancion c = (Cancion) listRepetidas.getSelectedValue();
        if(c == null)
        {
            JOptionPane.showMessageDialog(this, "Debes seleccionar primero " + "una canción para eliminarla");
        }
        else
        {
            if(JOptionPane.showConfirmDialog(this, "Estas seguro de eliminar" + "la canción " + c.toString()) == JOptionPane.OK_OPTION)
            {
                File f = c.getFile();
                f.delete();
                s.similares.remove(c);
                this.repaint();
            }
        }
    }// GEN-LAST:event_mnuDeleteSongActionPerformed

    private void mnuListenSongActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_mnuListenSongActionPerformed
        synchronized(this)
        {
            if(playing != null)
                playing.stop();
            Cancion c = (Cancion) listRepetidas.getSelectedValue();
            if(c == null)
            {
                JOptionPane.showMessageDialog(this, "Debes seleccionar primero " + "una canción");
            }
            else
            {
                playing = MusicPlayer.playSong(c, new Runnable()
                {
                    public void run()
                    {
                        if(playing != null && playing.termino)
                            cmdStopActionPerformed(null);
                    }
                });
                playing.play();
                cmdStop.setVisible(true);
            }
        }
    }// GEN-LAST:event_mnuListenSongActionPerformed

    private void cmdStopActionPerformed(java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_cmdStopActionPerformed
        playing.stop();
        cmdStop.setVisible(false);
    }// GEN-LAST:event_cmdStopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCancion;
    private javax.swing.JList listRepetidas;
    private javax.swing.JMenuItem mnuDeleteSong;
    private javax.swing.JMenuItem mnuListenSong;
    private javax.swing.JPopupMenu popLista;
    // End of variables declaration//GEN-END:variables

}
